disabled_rules:
  - nesting
  - trailing_whitespace
  - vertical_whitespace
opt_in_rules:
  - attributes
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - number_separator
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline

excluded:
  - Pods
  - MCTDataStructuresTests

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
